package com.searchmd.searchmd.controller;



import com.searchmd.searchmd.models.Patienttable;
import com.searchmd.searchmd.models.Appointmenttable;
import com.searchmd.searchmd.models.AppointmenttableRepository;
import com.searchmd.searchmd.models.PatientRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.NoSuchElementException;
import java.util.logging.Logger;

@Controller // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:3000/")
@RequestMapping(path="/appointment") // This means URL's start with /appointment (after Application path)
public class AppointmentController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    
    //Logger logger = Logger.getLogger(UserController.class.getName());

    private AppointmenttableRepository repository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewAppointment (@RequestParam Integer patientId, @RequestParam Integer doctorId, @RequestParam String appDate) throws ParseException {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Appointmenttable appointmentTable = new Appointmenttable();
        appointmentTable.setPatientid(patientId);
        appointmentTable.setDoctorid(doctorId);
        //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        LocalDateTime date = LocalDateTime.parse(appDate); // date time should be of format yyyy-MM-ddTHH:mm:ss
        System.out.println((date));
        appointmentTable.setAppdate(date);
        repository.save(appointmentTable);

        return "Saved Appointment";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Appointmenttable> getAllAppointments() {
        // This returns a JSON or XML with the users
        //logger.log(Level.INFO,"In get all usermethod");
        
        return repository.findAll();
    }

    @PostMapping(path = "/update")
    public @ResponseBody boolean updateAppointment (@RequestParam Integer appId, @RequestParam Integer patientId, @RequestParam Integer doctorId, @RequestParam String appDate) throws ParseException {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        boolean UpdateStatus = true;
        try{
            Appointmenttable appointmentTable = repository.findById(appId).get();
            appointmentTable.setPatientid(patientId);
            appointmentTable.setDoctorid(doctorId);
            //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            LocalDateTime date = LocalDateTime.parse(appDate); // date time should be of format yyyy-MM-ddTHH:mm:ss
            System.out.println((date));
            appointmentTable.setAppdate(date);
            repository.save(appointmentTable);
        }
        catch(NoSuchElementException e){
            UpdateStatus = false;
        }

        return UpdateStatus;
    }
    @PostMapping(path = "/cancel")
    public @ResponseBody boolean cancelAppointment (@RequestParam Integer appId){
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        boolean UpdateStatus = true;
        try{
            Appointmenttable appointmentTable = repository.findById(appId).get();
            repository.delete(appointmentTable);
        }
        catch(NoSuchElementException e){
            UpdateStatus = false;
        }

        return UpdateStatus;
    }

    @GetMapping("/getDocAppointments")
    public @ResponseBody Iterable<Appointmenttable> getAppointmentByDocId(@RequestParam int docid) {
        return repository.getAppointmentsByDocId((docid));
    }

    @GetMapping("/getPatientAppointments")
    public @ResponseBody Iterable<Appointmenttable> getAppointmentByPatientId(@RequestParam int patientId) {
        return repository.getAppointmentsByPatientId(patientId);
        
    }

    @GetMapping("/getAppointmentsByDate")
    public @ResponseBody Iterable<Appointmenttable> getAppointmentByDate(@RequestParam String date) {
        System.out.println(date);
        return repository.getAppointmentsByDate(date);
    }

    
}


